FROM public.ecr.aws/lambda/python:3

RUN yum update -y

RUN yum install -y \
    gcc \
    gcc-c++ \
    openssl-devel \
    zlib-devel \
    libffi-devel && \
    yum -y clean all


COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN yum remove -y gcc gcc-c++ && yum -y clean all && rm -rf /var/cache/yum

COPY . .

CMD [ "{{cookiecutter.adapter_code}}.app.handler" ]
